[package]
name = "pysandbox-native"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
name = "pysandbox_native"
crate-type = ["cdylib"]

[dependencies]
interprocess.workspace = true
pyo3.workspace = true
pyo3-async-runtimes.workspace = true
pysandbox-protocol = { path = "../pysandbox-protocol" }
pysandbox-sandboxd = { path = "../pysandbox-sandboxd" }
tokio.workspace = true

[build-dependencies]
pysandbox-sandboxd = { path = "../pysandbox-sandboxd" }
tokio.workspace = true
